cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart_view, clear_cart_view

app_name = 'cart'


urlpatterns = [
    path('', cart_detail_view, name="cart_detail"),
    path('add/<int:product_id>/', add_to_cart_view, name="add_to_cart"),
    path('remove/<int:product_id>/', remove_from_cart_view, name="remove_from_cart"),
    path('clear/', clear_cart_view, name="clear_cart"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('',  include('pages.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls', namespace="cart_url")),
    path('order/', include('orders.urls')),
    path('blog/', include('blogs.urls', namespace="blog_url")),
    path('media/', include('cart.urls')),


    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/forms.py
from django import forms


class AddToCart(forms.Form):
    QUANTITY_CHOICES = [(i, str(i)) for i in range(30)]

    quantity = forms.TypedChoiceField(choices=QUANTITY_CHOICES, coerce=int)

    inplace = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from .forms import AddToCart
from .cart import Cart
from products.models import Products


def cart_detail_view(request):
    cart = Cart(request)
    for item in cart:
        item['product_update_quantity_form'] = AddToCart(initial={
            'inplace': True,
            'quantity': item['quantity']
        })
    return render(request, 'cart/cart_detail.html', {'cart': cart})


@require_POST
def add_to_cart_view(request, product_id):
    cart = Cart(request)

    product = get_object_or_404(Products, id=product_id)
    form = AddToCart(request.POST)

    if form.is_valid():
        cleandata = form.cleaned_data
        quantity = cleandata['quantity']
        cart.add(product, quantity, replace_quantity=cleandata['inplace'])

    return redirect('cart:cart_detail')


def remove_from_cart_view(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Products, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def clear_cart_view(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load i18n %}
{% load convert_number %}
{% load humanize %}

{% block page_tilte %}
    سبد خرید
{% endblock %}

{% block content %}
    <!-- Main Wrapper Start -->
    <div class="container-fluid bg-light">
        {% translate "cart" as page_title %}
        {% include "page_title.html" with page_name=page_title %}

        <div class="row bg-white p-1 pt-5">
            <div class="col-sm-12 mt-5 mb-5">
                <div class="container">
                    <div class="row">
                        <div class="col-sm-12 col-lg-8 d-flex flex-column">
                            <div class="row no-gutters">
                                <div class="col-sm-12">
                                    <div class="">
                                        <table class="table table-responsive">
                                            <thead>
                                            <tr>
                                                <th>&nbsp;</th>
                                                <th>عکس محصول</th>
                                                <th>نام محصول</th>
                                                <th>قیمت</th>
                                                <th>مقدار</th>
                                                <th>مجموع</th>
                                            </tr>
                                            </thead>
                                            <tbody class="">
                                            {% for item in cart %}
                                                <tr class="tr-border">
                                                    <td class="product-remove text-right"><a
                                                            href="{% url 'cart:remove_from_cart' item.product_obj.id %}"><i
                                                            class="flaticon flaticon-cross"></i></a>
                                                    </td>
                                                    <td class="product-thumbnail text-right">
                                                        <img src="{{ item.product_obj.image.url }}"
                                                             class="w-100"
                                                             alt="Product Thumnail w-100">
                                                    </td>
                                                    <td class="product-name wide-column p-3">
                                                        <h3>
                                                            <a href="{% url 'product_detail' item.product_obj.id %}">{{ item.product_obj.title }}</a>
                                                        </h3>
                                                    </td>
                                                    <td class="product-price">
                                                        <span class="product-price-wrapper">
                                                            <span class="money">{{ item.product_obj.price|intcomma:False|english_to_persian }}</span>
                                                        </span>
                                                    </td>
                                                    <td class="product-quantity">
                                                        <form action="{% url 'cart:add_to_cart' item.product_obj.id %}"
                                                              method="post">
                                                            {% csrf_token %}
                                                            <div class="d-flex">
                                                                <div class="quantity">
                                                                    <input type="number" class="quantity-input"
                                                                           name="quantity"
                                                                           id="qty-1" value="{{ item.quantity }}"
                                                                           min="1">
                                                                    {{ item.product_update_quantity_form.inplace }}
                                                                </div>
                                                                <button type="submit" class="btn btn-success">
                                                                    <i class="fa fa-refresh"></i>
                                                                </button>
                                                            </div>
                                                        </form>
                                                    </td>
                                                    <td class="product-total-price p-1">
                                                        <span class="product-price-wrapper">
                                                        <span class="money">{{ item.total_price|intcomma:False|english_to_persian }} {% trans '$' %}</span>
                                                        </span>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                            <div class="d-block pt-2  mt-3">
                                <div class="col-sm-6 text-left">
                                    <a href="{% url 'cart:clear_cart' %}" class="btn bg-danger text-white">خالی کردن سبد
                                        خرید
                                    </a>
                                </div>
                            </div>
                        </div>
                        <!-- cart for pay -->
                        <div class="col-sm-12 c-mt-sm-5 mt-sm-5 mt-lg-0 col-lg-4">
                            <div class="cart-collaterals">
                                <div class="cart-totals">
                                    <h5 class="mb-4 text-center">مجموع</h5>
                                    <div class="cart-calculator">
                                        <div class="d-flex flex-wrap total-price">
                                            <div class="cart-calculator-item-head">
                                                <span>جمع کل</span>
                                            </div>
                                            <div class="cart-calculator-item-value">
                                                <span class="product-price-wrapper">
                                                <span class="money">{{ cart.get_total_price|intcomma:False|english_to_persian }} {% trans '$' %}</span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <a href="{% url 'order_detail' %}" class="btn-submit text-decoration-none">
                                        {% translate "order by" %}
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include "end_container.html" %}
    </div>
    <!-- Main Wrapper End -->
{% endblock %}