blogs/urls.py
from django.urls import path
from .views import BlogView, get_user_search, post_detail_view, blog_404, category_post_view

app_name = 'blog'

urlpatterns = [
    path('', BlogView.as_view(), name="home_blog"),
    path('search/', get_user_search, name="search_in_blog"),
    path('category/<int:category_id>/', category_post_view, name="blog_post_list"),
    path('post/<int:post_id>/', post_detail_view, name="post_detail"),
    path('blognotfind/', blog_404, name="not_find_page"),
]

cart/urls.py
from django.urls import path
from .views import cart_detail_view, add_to_cart_view, remove_from_cart_view, clear_cart_view

app_name = 'cart'


urlpatterns = [
    path('', cart_detail_view, name="cart_detail"),
    path('add/<int:product_id>/', add_to_cart_view, name="add_to_cart"),
    path('remove/<int:product_id>/', remove_from_cart_view, name="remove_from_cart"),
    path('clear/', clear_cart_view, name="clear_cart"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('',  include('pages.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls', namespace="cart_url")),
    path('order/', include('orders.urls')),
    path('blog/', include('blogs.urls', namespace="blog_url")),
    path('media/', include('cart.urls')),


    path('rosetta/', include('rosetta.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/_base_blog.html
{% load static %}
{% load i18n %}
{% load humanize %}
{% load convert_number %}

<!doctype html>
<html lang="pa">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block page_tilte %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap-rtl.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <script src="https://kit.fontawesome.com/9d274832ee.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
</head>
<body class="rtl">

<!-- start top nav -->
<div class="container-fluid bg-top-nav">
    <div class="row">
        <div class="col-sm-12 mt-3">
            <div class="container">
                <div class="row nav-blog no-gutters">
                    <div class="col-md-2 text-center pt-3 pr-2 text-right d-none d-md-block">
                        <p class="hashtag-title">هشتگ های داغ</p>
                    </div>
                    <div class="col-sm-12 col-md-10 nav-hashtag pt-4">
                        <ul class="d-flex justify-content-center align-items-center">
                            {% include "blogs/category_.html" %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3 pb-3">
        <div class="col-sm-12">
            <div class="container">
                <div class="row ">
                    <div class="col-sm-12 text-center pt-3 px-5 text-center">
                        <div>
                            <form action="{% url 'blog:search_in_blog' %}" method="GET">
                                {% csrf_token %}
                                <div class="input-group mb-3">
                                    <input type="text" name="title" class="form-control" placeholder="{% translate "search of my 100000 recent" %}">
                                    <div class="input-group-append">
                                        <button class="btn btn-success px-md-5" type="submit"><span class="flaticon flaticon-magnifying-glass-icon"></span></button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- end top nav -->

<!-- start body -->
{% block content %} {% endblock %}
<!-- end body -->

<!-- start footer -->
<footer class="container-fluid bg-light mt-3 p-4 mb-5">
    <div class="row">
        <div class="col-sm-12">
            <div class="container news-latter">
                <div class="row">
                    <div class="col-sm-12 col-md-3 join-news d-flex justify-content-center flex-column">
                        <h6>با عضویت در خبرنامه</h6>
                        <p>با عضویت از <span class="text-danger">30 درصد</span> تخفیف بهرمند شوید</p>
                    </div>
                    <div class="col-sm-12 col-md-4 offer-news d-flex justify-content-center">
                        <p><strong>به 226,000 مخاطب ما</strong> بپیوندین و از تخفیف های ویژه هفتگی مخصوص مخاطبین خبرنامه بهرمند شوید</p>
                    </div>
                    <div class="col-sm-12 col-md-5 email-news d-flex justify-content-center">
                        <div class="input-group">
                            <input type="text" class="form-control input-footer-news" placeholder="آدرس ایمیل...">
                            <div class="input-group-append">
                                <button class="btn btn-danger px-3 form-control" type="button">عضویت</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <div class="container">
                <div class="row main-section-footer main-section-footer-blog">
                    <div class="col-sm-12 d-flex justify-content-around mb-3">
                        <a href="{% url 'home' %}" class="text-decoration-none text-dark">
                            <h5>فروشگاه ما</h5>
                        </a>
                        <a href="{% url 'home' %}" class="text-decoration-none text-dark">
                            <h5>خدمات مشتریان</h5>
                        </a>
                        <a href="{% url 'singup' %}" class="text-decoration-none text-dark">
                            <h5>حساب کاربری</h5>
                        </a>
                        <a href="#" class="text-decoration-none text-dark">
                            <h5>فرصت‌های همکاری</h5>
                        </a>
                        <a href="#" class="text-decoration-none text-dark">
                            <h5>باز نشر مطالب</h5>
                        </a>
                        <div>
                            <ul class="nav">
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-decoration-none" href="#">
                                        <h4><i class="fa fa-telegram"></i></h4>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-decoration-none" href="#">
                                        <h4><i class="fa fa-instagram"></i></h4>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark text-decoration-none" href="#">
                                        <h4><i class="fa fa-twitter"></i></h4>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->


<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="{% static 'js/owl.carousel.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>

<script src="{% static 'js/main.js' %}" type="text/javascript"></script>

</div>
</body>
</html>

templates/_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Home page</h1>
</body>
</html>

templates/end_container.html
<div class="row">
            <div class="col-sm-12">
                <br>
                <br>
                <br>
            </div>
        </div>

templates/home.html
{% extends '_base.html' %}
{% load convert_number %}
{% load humanize %}
{% load i18n %}
{% block page_tilte %}
    صفحه خانه
{% endblock %}

{% block content %}
    <!-- start blog -->
    <div class="container mt-4">
        <div class="row">
            <p class="s-title d-inline">{% translate 'last products' %}</p>
        </div>
        <div class="row d-flex justify-content-around align-items-center">
            {% for product in products %}
                <div class="col-xl-3 col-md-4 col-sm-6 c-col-sm-6 mb-3">
                    <div class="card custom-card">
                        <div class="card-banner">
                            <a href="{{ product.get_absolute_url }}">
                                <img src="{{ product.image.url }}"
                                     alt="Products" class="w-100">
                            </a>
                            <span class="position-absolute bg-danger product-offer">
                                    تخفیف ویژه
                                </span>
                        </div>
                        <div class="card-body d-flex justify-content-center align-items-center flex-column custom-card-body">
                            <a href="{{ product.get_absolute_url }}" class="text-dark text-decoration-none">
                                <h5 class="product-title mt-2">{{ product.title }}</h5>
                            </a>
                            <p class="card-text price mt-2">
                                {#                                        <span class="p-s-first"><s>{{ product.price|intcomma:False|english_to_persian }}</s></span>#}
                                {#                                        <span class="p-s-second">-</span>#}
                                <span class="p-s-third">{{ product.price|intcomma:False|english_to_persian }}</span>

                            </p>
                            <div>
                                <form class="" method="post" action="{% url 'cart:add_to_cart' product.id %}">
                                    {% csrf_token %}
                                    <input type="hidden" value="1" name="quantity">
                                    <button type="submit"
                                            class="btn btn-success">{% trans 'add to shop card' %}</button>
                                </form>
                            </div>

                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- end blog -->
    <!-- start blog -->
    <div class="container mt-4">
        <div class="row">
            <p class="s-title d-inline">{% translate 'Recent content' %}</p>
        </div>
        <div class="row d-flex justify-content-around mt-2">
            {% for post in posts %}
                <div class="c-col-sm-6 col-sm-5 col-md-3 mb-2 blog-post">
                    <a href="{{ post.get_absolute_url }}" class="text-dark text-decoration-none">
                        <div class="card w-100 h-100">
                            <img class="card-img-top" src="{{ post.image.url }}" alt="Card image cap">
                            <div class="card-body">
                                <p class="card-text">{{ post.title }}</p>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
    <!-- end blog -->
{% endblock %}

templates/page_title.html
<div class="row">
            <div class="col-sm-12 text-center w-100 title-shop-cart">
                <h3>{{ page_name }}</h3>
            </div>
        </div>